---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: konflux-devlake

resources:
  # - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - mcp-server-deployment.yaml
  - mcp-server-service.yaml
  - route.yaml

commonLabels:
  app: konflux-devlake-mcp
  version: v1.0.0

images:
  - name: konflux-mcp-server
    newName: quay.io/flacatus/mcp-lake
    newTag: "1.0.0"
