---
apiVersion: v1
kind: Namespace
metadata:
  name: konflux-devlake
  labels:
    name: konflux-devlake
    app: konflux-devlake-mcp
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: devlake
    devlakeComponent: ui
